#! /bin/sh

BACKGROUND=~/Backgrounds

sxhkd &

bspc monitor -d I II III IV

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox state=floating

feh --bg-center $BACKGROUND
wal -a 70 -i $BACKGROUND

compton  --config ~/.config/compton/compton.conf
xrdb -merge ~/.cache/wal/colors.Xresources

polybar example &
